"""coluna de controle do job

Revision ID: 12a70cbc3426
Revises: 05c82d02b05d
Create Date: 2026-03-27 06:52:58.849537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '12a70cbc3426'
down_revision: Union[str, Sequence[str], None] = '05c82d02b05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users_history',
        sa.Column('notification_inactivity',
        sa.Boolean(),
        nullable=False,
        default=False,
        server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_history','notification_inactivity')
    # ### end Alembic commands ###
